services:
  - type: web
    runtime: static     
    name: Frontkick 
    env: node              
    branch: main           
    buildCommand: "npm install && npm run build"
    staticPublishPath: "dist/frontkick"  
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
