services:
  - type: static_site     # despliegue estático sobre CDN
    name: Frontkick # puedes llamarlo como quieras
    env: node              # para que Render ejecute npm
    branch: main           # rama que despliega
    buildCommand: "npm install && npm run build"
    publishPath: "dist/frontkick"  # ¡mismo que outputPath!
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
